### PR TITLE
Added Calculator Utility

### PR DESCRIPTION
**Pull request by jshrq**

### CODE REVIEW

**Review by RoCS2024 — COMMENTED** [review]
Kindly try to test when an input number has character on it. I suppose this will break the program. If so, kindly fix it.

**Comment by jshrq** [comment]
> Kindly try to test when an input number has character on it. I suppose this will break the program. If so, kindly fix it.

sir, already tested the program by inputting characters and it loops until the user entered a valid number.

**Review by RoCS2024 — CHANGES_REQUESTED** [review]
check my comment

**Review by RoCS2024 — APPROVED** [review]
all good

**Pull request merged**
